import { defineConfig } from 'vite-plus'

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  pack: {
    dts: {
      tsgo: true,
    },
    exports: true,
  },
  lint: {
    options: {
      typeAware: true,
      typeCheck: true,
    },
    plugins: ['unicorn', 'eslint', 'typescript', 'oxc', 'import', 'promise', 'react', 'react-perf'],
    categories: {
      correctness: 'deny',
      suspicious: 'warn',
    },
    rules: {
      'no-useless-rename': 'warn',
      'arrow-body-style': 'warn',
      'no-var': 'deny',
      'no-shadow': 'off',
      'no-unused-vars': [
        'warn',
        {
          args: 'after-used',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      'import/export': 'deny',
      'import/no-duplicates': 'warn',
      'import/no-empty-named-blocks': 'warn',
      'import/no-cycle': 'deny',
      'import/no-named-default': 'warn',
      'import/namespace': 'off',
      'import/named': 'off',
      'import/default': 'off',
      'import/no-named-as-default-member': 'off',
      'import/no-named-as-default': 'off',
      'import/no-unresolved': 'off',
      'import/no-unassigned-import': 'off',
      'typescript/no-inferrable-types': 'warn',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/array-type': ['warn', { default: 'array-simple' }],
      'typescript/consistent-type-imports': [
        'error',
        {
          prefer: 'type-imports',
          fixStyle: 'inline-type-imports',
          disallowTypeAnnotations: false,
        },
      ],
      'typescript/no-confusing-non-null-assertion': 'error',
      'typescript/no-extraneous-class': 'error',
      'typescript/no-explicit-any': 'deny',
      'typescript/no-unnecessary-type-constraint': 'warn',
      'typescript/no-redundant-type-constituents': 'warn',
      'typescript/no-useless-empty-export': 'warn',
      'typescript/no-extra-non-null-assertion': 'deny',
      'typescript/no-non-null-asserted-optional-chain': 'deny',
      'typescript/prefer-as-const': 'warn',
      'typescript/no-duplicate-enum-values': 'deny',
      'typescript/triple-slash-reference': 'deny',
      'typescript/no-misused-new': 'deny',
      'typescript/no-this-alias': 'warn',
      'typescript/no-unsafe-argument': 'deny',
      'typescript/no-unsafe-assignment': 'deny',
      'typescript/no-unsafe-call': 'deny',
      'typescript/no-unsafe-member-access': 'deny',
      'typescript/no-unsafe-return': 'deny',
      'typescript/no-unsafe-declaration-merging': 'deny',
      'typescript/no-unsafe-type-assertion': 'off',
      'typescript/prefer-function-type': 'error',
      'typescript/prefer-nullish-coalescing': 'error',
      'typescript/await-thenable': 'deny',
      'typescript/no-floating-promises': 'deny',
      'typescript/no-for-in-array': 'deny',
      'typescript/no-implied-eval': 'deny',
      'typescript/no-base-to-string': 'warn',
      'typescript/restrict-template-expressions': 'warn',
      'typescript/unbound-method': 'warn',

      'unicorn/no-array-for-each': 'warn',
      'unicorn/prefer-array-find': 'warn',
      'unicorn/require-post-message-target-origin': 'off', // causes shared workers issues

      'promise/param-names': 'deny',
      'promise/no-new-statics': 'deny',
      'promise/valid-params': 'deny',
    },
  },
  fmt: {
    tabWidth: 2,
    useTabs: false,
    semi: false,
    trailingComma: 'all',
    singleQuote: true,
    printWidth: 100,
    experimentalSortPackageJson: true,
    experimentalSortImports: {
      partitionByComment: true,
    },
  },
})
